### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by jhr007** [hilotus/ember-cli-coreweb-ui#1]
I was googling for ember-cli web interfaces and came across this repo.  

What does this project do? The readme needs a description of what this project does. :D

ember-cli-coreweb-ui too 

FYI, You can use https://github.com/poetic/ember-cli-github-pages or https://github.com/dukex/ember-cli-deploy-github to deploy a build of an ember app(or an addon's dummy app) to the 'gh-pages' branch. 

This will let you show off a demo of the app on github.io like: https://miguelcobain.github.io/ember-fullscreen/

Cheers

**Comment by weilluo** [comment]
@jhr007 Thanks,  At first I want to build an ember component collection. Now, it contains `{{cw-button}}` and `{{nav-ui}}`, but it not completed. I'm not sure I will focus on it in the future.
